### ISSUE TITLE
Issue session 04.11 on the face dataframe

### ISSUE THREAD

**Issue by LinhRamirez** [DeAngelisA/ISSS21#6]
RStudio is not able to read the face dataframe we use at the beginning. 

I did the following runs:

Sys.setenv(R_REMOTES_STANDALONE = "true")
remotes::install_github("kosukeimai/qss-package")
data(package = "qss")
data(elections, package = "qss") # load e.g. the elections data
vignette(package = "qss") # list all vignettes
browseVignettes("qss") # list vignettes and R code
vignette("causality", package = "qss") # show the vignette for the Causality chapter

which gave me a positive outcome and also showed me, that the data frames of the qss package are on my RStudio
<img width="1096" alt="1" src="https://user-images.githubusercontent.com/91264824/139837367-6ca28a0d-e1f3-466f-acf4-d4dde50e9b39.PNG">
:

And then, when I am writing the command **face <- read.csv("face.csv")** the error message comes: 
![image](https://user-images.githubusercontent.com/91264824/139837474-bf8f8a7b-e4d7-4ba6-8179-91f2db3b531c.png)

did anybody had this problem as well? 

I am already accepting, that I am having a never ending story with the qss package...

**Comment by DeAngelisA** [comment]
@LinhRamirez : try with the following code

`library(qss)   # load the QSS package
data(face)      # load the "face" data
`

**Comment by LinhRamirez** [comment]
Thank you it worked!
