### ISSUE TITLE
ifelse condition

### ISSUE THREAD

**Issue by SimonSchmitter** [DeAngelisA/ISSS21#7]
Does anyone know, how to do an ifelse conditon with variables for "if" and "else" arguments. If I put the first variable as the argument that should result if my condition is true, it works, but as soon as I put the "else" argument, R just again takes the "if" variable.:

condition, x,y = variables 

> ifelse (condition == 1, x, y)

R just always takes x, even if there isn't a 1 in "condition".

If I try it with a single word like "no" instead of y....

> ifelse (Condition == 1, x, "no")

.. it perfectly works.

Does anyone has a solution for this? Thanks a lot.

**Comment by DeAngelisA** [comment]
I am not sure I can see the problem here. If R always returns x, to me that means that the condition is always satisfied. It is hard to say without having some code or a reproducible example to look at. I paste here below some code to show the functioning of `ifelse()` with continuous and categorical variables, maybe comparing the code can help. 

```r
library(tidyverse)
dat <- tibble(
  v1 = rnorm(n = 100, mean = 0, sd = 1),
  v2 = sample(size = 100, x = c("group1", "group2"), replace = TRUE)
)
dat %>% 
  mutate(
    v3_cont = ifelse(test = v1 > 0, yes = 1, no = 0), 
    v4_cat  = ifelse(test = v2 == "group1", yes = "yes", no = "no") 
  )
```

Which returns the following: 
```r
# A tibble: 100 x 4
        v1 v2     v3_cont v4_cat
     <dbl> <chr>    <dbl>  <dbl>
 1  1.04   group1       1      1
 2  0.756  group2       1      0
 3 -0.509  group1       0      1
 4  0.658  group1       1      1
 5  0.0351 group1       1      1
 6  0.786  group2       1      0
 7  0.447  group2       1      0
 8  0.694  group2       1      0
 9 -0.442  group1       0      1
10 -0.392  group2       0      0
# ... with 90 more rows
```

**Comment by SimonSchmitter** [comment]
Thank you for your help! I've had a little error, which I in fact found after a while, but then didn't quite knew where to delete this question on github. So I just tried to close the issue.

Nevertheless thanks very much!
